object Versions {

    const val gradlePlugin = "4.2.1"
    const val kotlin = "1.6.10"
    const val timber = "4.7.1"
    const val appCompat = "1.3.0"
    const val material = "1.3.0"
    const val constraintLayout = "1.1.3"
    const val jUnit = "4.13.2"
    const val junit_ext = "1.1.1"
    const val androidJunit = "1.1.3"
    const val androidExpresso = "3.4.0"
    const val composeVersion = "1.2.0-alpha05"
    const val androidApplicationPlugin = "7.1.0"
    const val androidLibraryPlugin = "7.1.0"
    const val kotlinAndroidPlugin = "1.5.21"
    const val androidXCore = "1.7.0"
    const val lifecycle = "2.4.1"
    const val activityCompose = "1.4.0"
    const val koin_version = "3.1.5"
    const val retrofit_adapter = "0.9.2"
    const val okhttp_logger = "4.7.2"
    const val okhttp_bom = "4.9.0"
    const val mockito_version = "2.27.0"
    const val androidx_core_test = "2.1.0"
    const val leak_canary = "2.7"

    const val coroutines = "1.3.7"
    const val retrofit = "2.9.0"
    const val lifecycle_version = "2.5.0-alpha04"
    const val gson = "2.8.7"
    const val lifecycle_ext = "2.5.0-alpha04"

    const val espresso_core = "3.3.0"
    const val fragment_version = "1.3.0-alpha06"
    const val dex_maker_version = "2.28.1"
    const val paging_compose_version = "1.0.0-alpha14"
    const val coil_version = "0.12.0"
    const val version_code = 1
}